### ISSUE TITLE
Can't matrix if you go SSD and rejoin.

### ISSUE THREAD

**Issue by Sinbest** [LoneStarF13/LoneStar#53]
## Round ID:

698

## Reproduction:

Join the game.

Go SSD.

Rejoin and try to matrix.

Fail.

**Comment by buffyuwu** [comment]
You're describing joining the game and SSD'ing shortly after. The timer used to be 5 minutes for such a thing to prevent people joining -> quitting right away. Now it's been lowered to 2 minutes! Still, this is intentional.

Thank you for reaching out though!!!! Had this have been a bug bug you would have contributed greatly in making Lone Star much more awesome by bringing it to our attention!! :)
